import type { Metadata } from "next";
import "./globals.css";
import Mainlayout from "./Components/Mainlayout";


export const metadata: Metadata = {
  title: "My Chatting App",
  description: "Generated by create next app",
};
//
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Mainlayout>{children}</Mainlayout>
        
        </body>
    </html>
  );
}
